# Generated by Django 4.1.5 on 2023-01-30 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateField()),
                ('symptoms', models.CharField(max_length=256)),
                ('request_date', models.DateField()),
                ('appointment_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments_app.appointmentstatus')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.patient')),
            ],
        ),
    ]
