# Generated by Django 4.1.5 on 2023-01-30 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_status',
            field=models.ForeignKey(default='Requested', on_delete=django.db.models.deletion.CASCADE, to='appointments_app.appointmentstatus', to_field='status'),
        ),
        migrations.AlterField(
            model_name='appointmentstatus',
            name='status',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
