# Generated by Django 4.1.5 on 2023-02-26 13:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
        ('appointments_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_date', models.DateTimeField()),
                ('symptoms', models.CharField(max_length=256)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.patient')),
                ('wishlist_status', models.ForeignKey(default='Waiting', on_delete=django.db.models.deletion.CASCADE, to='appointments_app.wishliststatus', to_field='status')),
            ],
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(condition=models.Q(('wishlist_status', 'Waiting'), ('wishlist_status', 'Available'), ('wishlist_status', 'Booked'), _connector='OR'), fields=('doctor', 'appointment_date', 'wishlist_status'), name='unique_wishlist_record'),
        ),
    ]
