# Generated by Django 4.1.5 on 2023-01-30 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_app', '0002_alter_appointment_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
