# Generated by Django 4.1.5 on 2023-02-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_app', '0003_alter_appointment_appointment_date_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(condition=models.Q(('appointment_status', 'Requested'), ('appointment_status', 'Confirmed'), _connector='OR'), fields=('doctor', 'appointment_date', 'appointment_status'), name='unique_appointment'),
        ),
    ]
