# Generated by Django 4.1.5 on 2023-02-10 22:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_app', '0004_appointment_unique_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 10, 22, 27, 26, 800638)),
        ),
    ]
