# Generated by Django 4.1.5 on 2023-02-10 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments_app', '0005_alter_appointment_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
